## **load data**

## **combine datasets**

In [4]:
import glob
import numpy as np
from PIL import Image

images = []
labels = []
genres = ['blues', 'classical', 'country', 'disco', 'hiphop', 
          'jazz', 'metal', 'pop', 'reggae', 'rock']

for genre in genres:
    # Find all .png files in the genre folder
    path = f'/Users/sophiekim/Desktop/1_spring/ds 6050/Data/images_original/{genre}/*.png'
    for file in glob.glob(path):
        img = Image.open(file).convert('RGB')
        img = img.resize((128, 128)) # Optional: resize for memory efficiency
        images.append(np.array(img))
        labels.append(genre)

# Convert to a single numpy array
X = np.array(images)

In [5]:
print(X)

[[[[255 255 255]
   [255 255 255]
   [255 255 255]
   ...
   [255 255 255]
   [255 255 255]
   [255 255 255]]

  [[255 255 255]
   [255 255 255]
   [255 255 255]
   ...
   [255 255 255]
   [255 255 255]
   [255 255 255]]

  [[255 255 255]
   [255 255 255]
   [255 255 255]
   ...
   [255 255 255]
   [255 255 255]
   [255 255 255]]

  ...

  [[255 255 255]
   [255 255 255]
   [255 255 255]
   ...
   [255 255 255]
   [255 255 255]
   [255 255 255]]

  [[255 255 255]
   [255 255 255]
   [255 255 255]
   ...
   [255 255 255]
   [255 255 255]
   [255 255 255]]

  [[255 255 255]
   [255 255 255]
   [255 255 255]
   ...
   [255 255 255]
   [255 255 255]
   [255 255 255]]]


 [[[255 255 255]
   [255 255 255]
   [255 255 255]
   ...
   [255 255 255]
   [255 255 255]
   [255 255 255]]

  [[255 255 255]
   [255 255 255]
   [255 255 255]
   ...
   [255 255 255]
   [255 255 255]
   [255 255 255]]

  [[255 255 255]
   [255 255 255]
   [255 255 255]
   ...
   [255 255 255]
   [255 255 255]
   [255 255

In [6]:
# Check the shape: (Number of images, Height, Width, Channels)
print("Shape:", X.shape) 

# Check if there is anything OTHER than white (255)
print("Min value:", X.min()) 
print("Max value:", X.max())
print("Average pixel value:", X.mean())

Shape: (999, 128, 128, 3)
Min value: 0
Max value: 255
Average pixel value: 123.50131073863577


## **convert audio files to numeric arrays**

## **model 1**

### **analysis of model 1**

## **model 2**

### **analysis of model 2**